/*
 * This file is generated by jOOQ.
 */
package com.tan.jooq.mysql.dao.tables;


import com.tan.jooq.mysql.dao.Indexes;
import com.tan.jooq.mysql.dao.Keys;
import com.tan.jooq.mysql.dao.Test;
import com.tan.jooq.mysql.dao.tables.records.UserPO;

import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function6;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row6;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserTB extends TableImpl<UserPO> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>test.user</code>
     */
    public static final UserTB USER = new UserTB();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserPO> getRecordType() {
        return UserPO.class;
    }

    /**
     * The column <code>test.user.id</code>.
     */
    public final TableField<UserPO, UInteger> ID = createField(DSL.name("id"), SQLDataType.INTEGERUNSIGNED.nullable(false).identity(true), this, "");

    /**
     * The column <code>test.user.name</code>. 用户名
     */
    public final TableField<UserPO, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(80).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "用户名");

    /**
     * The column <code>test.user.pwd</code>. 密码
     */
    public final TableField<UserPO, String> PWD = createField(DSL.name("pwd"), SQLDataType.VARCHAR(26).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "密码");

    /**
     * The column <code>test.user.isDeleted</code>.
     */
    public final TableField<UserPO, Byte> ISDELETED = createField(DSL.name("isDeleted"), SQLDataType.TINYINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>test.user.created</code>.
     */
    public final TableField<UserPO, String> CREATED = createField(DSL.name("created"), SQLDataType.VARCHAR(13).nullable(false).defaultValue(DSL.inline("0", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>test.user.updated</code>.
     */
    public final TableField<UserPO, String> UPDATED = createField(DSL.name("updated"), SQLDataType.VARCHAR(13).nullable(false).defaultValue(DSL.inline("0", SQLDataType.VARCHAR)), this, "");

    private UserTB(Name alias, Table<UserPO> aliased) {
        this(alias, aliased, null);
    }

    private UserTB(Name alias, Table<UserPO> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>test.user</code> table reference
     */
    public UserTB(String alias) {
        this(DSL.name(alias), USER);
    }

    /**
     * Create an aliased <code>test.user</code> table reference
     */
    public UserTB(Name alias) {
        this(alias, USER);
    }

    /**
     * Create a <code>test.user</code> table reference
     */
    public UserTB() {
        this(DSL.name("user"), null);
    }

    public <O extends Record> UserTB(Table<O> child, ForeignKey<O, UserPO> key) {
        super(child, key, USER);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Test.TEST;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.USER_NAME);
    }

    @Override
    public Identity<UserPO, UInteger> getIdentity() {
        return (Identity<UserPO, UInteger>) super.getIdentity();
    }

    @Override
    public UniqueKey<UserPO> getPrimaryKey() {
        return Keys.KEY_USER_PRIMARY;
    }

    @Override
    public UserTB as(String alias) {
        return new UserTB(DSL.name(alias), this);
    }

    @Override
    public UserTB as(Name alias) {
        return new UserTB(alias, this);
    }

    @Override
    public UserTB as(Table<?> alias) {
        return new UserTB(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserTB rename(String name) {
        return new UserTB(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserTB rename(Name name) {
        return new UserTB(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserTB rename(Table<?> name) {
        return new UserTB(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<UInteger, String, String, Byte, String, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function6<? super UInteger, ? super String, ? super String, ? super Byte, ? super String, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function6<? super UInteger, ? super String, ? super String, ? super Byte, ? super String, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
