/*
 * This file is generated by jOOQ.
 */
package com.tan.jooq.crud.h2;


import com.tan.jooq.crud.h2.tables.PoetTB;
import com.tan.jooq.crud.h2.tables.PoetryTB;
import com.tan.jooq.crud.h2.tables.records.PoetPO;
import com.tan.jooq.crud.h2.tables.records.PoetryPO;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * PUBLIC.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<PoetPO> PK_T_POET = Internal.createUniqueKey(PoetTB.POET, DSL.name("PK_T_POET"), new TableField[] { PoetTB.POET.ID }, true);
    public static final UniqueKey<PoetryPO> PK_T_POETRY = Internal.createUniqueKey(PoetryTB.POETRY, DSL.name("PK_T_POETRY"), new TableField[] { PoetryTB.POETRY.ID }, true);
}
