/*
 * This file is generated by jOOQ.
 */
package com.tan.jooq.crud.h2;


import com.tan.jooq.crud.h2.tables.PoetTB;
import com.tan.jooq.crud.h2.tables.PoetryTB;


/**
 * Convenience access to all tables in PUBLIC.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.POET</code>.
     */
    public static final PoetTB POET = PoetTB.POET;

    /**
     * The table <code>PUBLIC.POETRY</code>.
     */
    public static final PoetryTB POETRY = PoetryTB.POETRY;
}
