/*
 * This file is generated by jOOQ.
 */
package com.tan.jooq.mysql.dao;


import com.tan.jooq.mysql.dao.tables.MoneyTB;
import com.tan.jooq.mysql.dao.tables.UserTB;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in test.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index MONEY_NAME = Internal.createIndex(DSL.name("name"), MoneyTB.MONEY, new OrderField[] { MoneyTB.MONEY.NAME }, false);
    public static final Index USER_NAME = Internal.createIndex(DSL.name("name"), UserTB.USER, new OrderField[] { UserTB.USER.NAME }, false);
}
