/*
 * This file is generated by jOOQ.
 */
package com.tan.jooq.mysql.dao;


import com.tan.jooq.mysql.dao.tables.MoneyTB;
import com.tan.jooq.mysql.dao.tables.UserTB;


/**
 * Convenience access to all tables in test.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>test.money</code>.
     */
    public static final MoneyTB MONEY = MoneyTB.MONEY;

    /**
     * The table <code>test.user</code>.
     */
    public static final UserTB USER = UserTB.USER;
}
