spring:
  application:
    name: 051-redis-lettuce
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      password:
      lettuce:
        pool:
          max-idle: 6
          max-active: 32
          max-wait: 100
          min-idle: 4
