/*
 * This file is generated by jOOQ.
 */
package com.tan.jooq.h2;


import com.tan.jooq.h2.tables.Poet;
import com.tan.jooq.h2.tables.records.PoetRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * PUBLIC.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<PoetRecord> PK_T_POET = Internal.createUniqueKey(Poet.POET, DSL.name("PK_T_POET"), new TableField[] { Poet.POET.ID }, true);
}
