/*
 * This file is generated by jOOQ.
 */
package com.tan.jooq.h2;


import com.tan.jooq.h2.tables.Poet;


/**
 * Convenience access to all tables in PUBLIC.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.POET</code>.
     */
    public static final Poet POET = Poet.POET;
}
