/*
 * This file is generated by jOOQ.
 */
package com.tan.jooq.crud.h2.tables;


import com.tan.jooq.crud.h2.Keys;
import com.tan.jooq.crud.h2.Public;
import com.tan.jooq.crud.h2.tables.records.PoetPO;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import java.util.Collection;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PoetTB extends TableImpl<PoetPO> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>PUBLIC.POET</code>
     */
    public static final PoetTB POET = new PoetTB();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PoetPO> getRecordType() {
        return PoetPO.class;
    }

    /**
     * The column <code>PUBLIC.POET.ID</code>.
     */
    public final TableField<PoetPO, Integer> ID = createField(DSL.name("ID"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>PUBLIC.POET.NAME</code>.
     */
    public final TableField<PoetPO, String> NAME = createField(DSL.name("NAME"), SQLDataType.VARCHAR(20).nullable(false).defaultValue(DSL.field(DSL.raw("''"), SQLDataType.VARCHAR)), this, "");

    private PoetTB(Name alias, Table<PoetPO> aliased) {
        this(alias, aliased, (Field<?>[]) null);
    }

    private PoetTB(Name alias, Table<PoetPO> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>PUBLIC.POET</code> table reference
     */
    public PoetTB(String alias) {
        this(DSL.name(alias), POET);
    }

    /**
     * Create an aliased <code>PUBLIC.POET</code> table reference
     */
    public PoetTB(Name alias) {
        this(alias, POET);
    }

    /**
     * Create a <code>PUBLIC.POET</code> table reference
     */
    public PoetTB() {
        this(DSL.name("POET"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<PoetPO> getPrimaryKey() {
        return Keys.PK_T_POET;
    }

    @Override
    public PoetTB as(String alias) {
        return new PoetTB(DSL.name(alias), this);
    }

    @Override
    public PoetTB as(Name alias) {
        return new PoetTB(alias, this);
    }

    @Override
    public PoetTB as(Table<?> alias) {
        return new PoetTB(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public PoetTB rename(String name) {
        return new PoetTB(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PoetTB rename(Name name) {
        return new PoetTB(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public PoetTB rename(Table<?> name) {
        return new PoetTB(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PoetTB where(Condition condition) {
        return new PoetTB(getQualifiedName(), aliased() ? this : null, null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PoetTB where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PoetTB where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PoetTB where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PoetTB where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PoetTB where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PoetTB where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PoetTB where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PoetTB whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PoetTB whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
