spring:
  application:
    name: 056-influxdb-java
  influxdb:
    url: http://localhost:8086
    username:
    password:
    database:
    retention-policy: autogen
    connect-timeout: 10
    read-timeout: 30
    write-timeout: 10
    gzip: true
